version: "3.8"
services:
  portainer:
    image: "10.25.1.22:8082/ngc-local/basic/portainer-ce"
    restart: always
    environment:
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /operational_data/portainer:/data
